baseURL = "/"
relativeURLs = true
languageCode = "en-us"
ignoreFiles = [
    "/content/templates/*",
    "/content/private/*",
]
summaryLength = 20
paginate = 10
enableGitInfo = true
avatarURL = "images/rwiconblue.png"
dateFormat = "2006-01-02"

# https://orcid.org/0000-0002-1806-4294

[markup]
    [markup.tableOfContents]
        endLevel = 3
        ordered = true
        startLevel = 2
    [markup.highlight]
        noClasses = false
        anchorLineNos = false
        codeFences = true
        guessSyntax = true
        hl_Lines = ""
        lineAnchors = ""
        lineNoStart = 1
        lineNos = true
        lineNumbersInTable = true
        style = "dracula"
    [frontmatter]   # https://stackoverflow.com/questions/59655470/hugo-date-vs-publishdate
        lastmod = [":git", "updated"]
        publishDate = ["created"]
        date = ["created"]
    [markup.goldmark.renderer]
        unsafe = true


############################
## Comments
############################
# To configure Giscus, see layouts/partials/giscus.html